class LanguageConfig {
  static const Map<String, String> countryToLanguage = {
    '대한민국': 'ko',
    '일본': 'ja',
    '미국': 'en',
    '영국': 'en',
    '프랑스': 'fr',
    '독일': 'de',
    '이탈리아': 'it',
    '스페인': 'es',
    '브라질': 'pt',
    '인도': 'hi',
    '중국': 'zh',
    '호주': 'en',
    '캐나다': 'en',
    '멕시코': 'es',
    '아르헨티나': 'es',
    '러시아': 'ru',
    '터키': 'tr',
    '이집트': 'ar',
    '남아프리카': 'en',
    '태국': 'th',
    '네덜란드': 'en',
    '스웨덴': 'en',
    '노르웨이': 'en',
    '포르투갈': 'pt',
    '인도네시아': 'en',
    '말레이시아': 'en',
    '싱가포르': 'en',
    '뉴질랜드': 'en',
    '필리핀': 'en',
    '베트남': 'en',
    '우크라이나': 'en',
    '폴란드': 'en',
    '체코': 'en',
    '헝가리': 'en',
    '그리스': 'en',
    '이스라엘': 'en',
    '사우디아라비아': 'ar',
    'UAE': 'ar',
    '파키스탄': 'en',
    '방글라데시': 'en',
    '나이지리아': 'en',
    '케냐': 'en',
    '에티오피아': 'en',
    '모로코': 'ar',
    '콜롬비아': 'es',
    '페루': 'es',
    '칠레': 'es',
    '덴마크': 'en',
    '핀란드': 'en',
    '오스트리아': 'de',
  };

  static const Map<String, String> languageNames = {
    'ko': '한국어',
    'ja': '日本語',
    'en': 'English',
    'fr': 'Français',
    'de': 'Deutsch',
    'it': 'Italiano',
    'es': 'Español',
    'pt': 'Português',
    'hi': 'हिन्दी',
    'zh': '中文',
    'ru': 'Русский',
    'tr': 'Türkçe',
    'ar': 'العربية',
    'th': 'ภาษาไทย',
  };

  static String getLanguageCode(String country) =>
      countryToLanguage[country] ?? 'en';

  static String getLanguageName(String code) => languageNames[code] ?? code;

  // Timezone offset in hours from UTC (approximate, for time-of-day theme)
  static const Map<String, double> countryTimezone = {
    '대한민국': 9.0,
    '일본': 9.0,
    '미국': -5.0,
    '영국': 0.0,
    '프랑스': 1.0,
    '독일': 1.0,
    '이탈리아': 1.0,
    '스페인': 1.0,
    '브라질': -3.0,
    '인도': 5.5,
    '중국': 8.0,
    '호주': 10.0,
    '캐나다': -5.0,
    '멕시코': -6.0,
    '아르헨티나': -3.0,
    '러시아': 3.0,
    '터키': 3.0,
    '이집트': 2.0,
    '남아프리카': 2.0,
    '태국': 7.0,
    '네덜란드': 1.0,
    '스웨덴': 1.0,
    '노르웨이': 1.0,
    '포르투갈': 0.0,
    '인도네시아': 7.0,
    '말레이시아': 8.0,
    '싱가포르': 8.0,
    '뉴질랜드': 12.0,
    '필리핀': 8.0,
    '베트남': 7.0,
    '우크라이나': 2.0,
    '폴란드': 1.0,
    '체코': 1.0,
    '헝가리': 1.0,
    '그리스': 2.0,
    '이스라엘': 2.0,
    '사우디아라비아': 3.0,
    'UAE': 4.0,
    '파키스탄': 5.0,
    '방글라데시': 6.0,
    '나이지리아': 1.0,
    '케냐': 3.0,
    '에티오피아': 3.0,
    '모로코': 1.0,
    '콜롬비아': -5.0,
    '페루': -5.0,
    '칠레': -3.0,
    '덴마크': 1.0,
    '핀란드': 2.0,
    '오스트리아': 1.0,
  };

  static double getTimezoneOffset(String country) =>
      countryTimezone[country] ?? 0.0;
}
